python -m pdb scripts/finetune_singlegpu.py \
    --vla_path "openvla/openvla-7b" \
    --data_root_dir "./datasets/tensorflow_datasets_hanriu_500" \
    --dataset_name smlr_dataset \
    --run_root_dir "./checkpoints/debug_antonio" \
    --adapter_tmp_dir "./adapters_tmp" \
    --lora_rank 32 \
    --batch_size 2 \
    --grad_accumulation_steps 16 \
    --learning_rate 5e-4 \
    --image_aug False \
    --wandb_project openvla_finetune_mikhail \
    --wandb_entity botello_antonio-technical-university-of-munich  \
    --save_steps 1000  \
